### ISSUE TITLE
Select 'featured' use cases

### ISSUE THREAD

**Issue by elichad** [ResearchObject/ro-crate-2024#17]
If there are a lot of use cases, displaying them all on the homepage isn't practical.

We could pick 6 or so exemplary use cases to feature, using something like a `featured: true` tag on those pages.

The full list of use cases would still be displayed on the Use Cases page

**Comment by nsjuty** [comment]
We can prioritise some - maybe based on how much info they provide when they are approved for display. then maybe randomise so its not always the same ones. I think we want to disaply as many as possible?

**Comment by a-mile** [comment]
We'll pick 6 to tag as featured to start, can update after launch if needed.
