### ISSUE TITLE
DataCrate spec link broken

### ISSUE THREAD

**Issue by elichad** [ResearchObject/ro-crate-2024#19]
In `spec.yml`:

```
- title: DataCrate 1.0 review (imported from datacrate)
  url: https://docs.google.com/document/d/150SzIG8Zs3wecPTUue7wxKn6V26oi7rYucS5lxnmWZU/edit
```

links to a page saying "Sorry, the file you have requested has been deleted. Make sure you have the correct URL and the owner of the file hasn't deleted it."

![Screenshot of Google Docs error: Sorry, the file you have requested has been deleted. Make sure you have the correct URL and the owner of the file hasn't deleted it.](https://github.com/ResearchObject/ro-crate-2024/assets/20683271/22e4761c-532d-41be-975e-546205c6727a)

**Comment by elichad** [comment]
Can link to https://github.com/UTS-eResearch/datacrate/blob/master/spec/1.0/data_crate_specification_v1.0.md instead

**Comment by elichad** [comment]
Remove Datacrate and ROLite from specification sidebar (should still be listed on spec homepage)

**Comment by jmfernandez** [comment]
@elichad Maybe you can use a permalink instead https://github.com/UTS-eResearch/datacrate/blob/ba37cc707d48d3569663ab04f9d4f5c25dac6e34/spec/1.0/data_crate_specification_v1.0.md
