### ISSUE TITLE
Images broken in (1.2) spec

### ISSUE THREAD

**Issue by elichad** [ResearchObject/ro-crate-2024#21]
Images aren't displaying on the 1.2-DRAFT introduction page https://www.researchobject.org/ro-crate-2024/specification/1.2-DRAFT/introduction.html.

![](https://github.com/ResearchObject/ro-crate-2024/assets/20683271/3f07398e-2fd1-4c76-851c-b8f44d3c6976)

**Comment by jmfernandez** [comment]
It seems either the links are not properly built or the resources are not properly placed, because the built link points to https://www.researchobject.org/ro-crate-2024/specification/assets/img/crate1-folders.svg instead of https://www.researchobject.org/ro-crate-2024/assets/img/crate1-folders.svg
