### ISSUE TITLE
'Add your use case' page shows up twice in sidebar

### ISSUE THREAD

**Issue by elichad** [ResearchObject/ro-crate-2024#35]
And weirdly it doesn't show on local instance at all.

This is the technical page so it shouldn't be included in the sidebar.

![image](https://github.com/ResearchObject/ro-crate-2024/assets/20683271/d9c495ea-3bfa-4a93-bfa5-9d3edc4de15d)

**Comment by elichad** [comment]
Possible fix: add `type: hidden` to front matter (value could be anything, to override the default which is `type: domains`)

**Comment by a-mile** [comment]
@elichad exclude from build resolved this, good suggestion
