### ISSUE TITLE
Set up related pages

### ISSUE THREAD

**Issue by a-mile** [ResearchObject/ro-crate-2024#6]
For domains, tasks and roles, add related_pages to the page data:
![image](https://github.com/ResearchObject/ro-crate-2024/assets/62754573/04847659-fd75-402e-b7e7-2bce0a9a14e0)

Related pages can include other domains, tasks, and roles, as well as use cases, tools and tutorials.

**Comment by elichad** [comment]
I think these are set up now, but it would probably be good to check these over to see if they make sense - I didn't really know what to add for the ones I did.

**Comment by elichad** [comment]
Oh, I think they're missing for the task and role pages (or maybe just not needed)
