### ISSUE TITLE
Submit use case

### ISSUE THREAD

**Issue by a-mile** [ResearchObject/ro-crate-2024#8]
Create a use case submission form and make it available from the use cases main page. The form should collect title, description, url, logo image link, and a list of domains, tasks, and roles from which they can select any that apply. In addition, there is a free text area that can be used to add any that aren't listed. The submitter should have the option of attaching a markdown file for the use case contents.
A template should be available for download that guides the user through creating a markdown document.

**Comment by stain** [comment]
https://docs.google.com/forms/d/e/1FAIpQLScvphoh0Q0s4vY0gZCj26eBh1C30nn5y6RLvmpeow8qqC46Jw/viewform now linked from https://www.researchobject.org/ro-crate-2024/use_cases
